/*
 * SPDX-FileCopyrightText: 2026 OPPO
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * Git Diff subdirectory special test
 *
 * Verify that when opening Git Diff in the Git repository subdirectory:
 * 1. Create/modify files in subdirectories to make changes
 * 2. Open Git Diff in the subdirectory and it will load normally (it will not keep spinning)
 * 3. Always execute diff from the root directory of the Git repository to display changes in the entire repository
 * 4. Changes made in subdirectories can be found in the diff file list
 * 5. The caching mechanism is correct (the cache can be hit after closing and reopening)
 * 6. Clean up temporary files generated by testing
 */
import type { AutotestContext, TestResult } from './types'
import { buildChangeDirectoryCommand, type TerminalShellKind } from '../utils/terminal-command'

/** The name of the test marker file created in the subdirectory */
const TEST_MARKER_FILE = '__autotest_diff_marker.txt'

async function resolveTerminalShellKind(terminalId: string): Promise<TerminalShellKind | undefined> {
  try {
    return (await window.electronAPI.terminal.getInputCapabilities(terminalId)).shellKind
  } catch {
    return undefined
  }
}

export async function testGitDiffSubdir(ctx: AutotestContext): Promise<TestResult[]> {
  const { log, sleep, waitFor, assert, cancelled, terminalId, rootPath } = ctx
  const results: TestResult[] = []
  const _assert = (name: string, ok: boolean, detail?: Record<string, unknown>) => {
    assert(name, ok, detail)
    results.push({ name, ok, detail })
  }

  log('git-diff-subdir:start', { suite: 'GitDiffSubdir', rootPath })

  const getGitDiffApi = () => window.__onwardGitDiffDebug
  const platform = window.electronAPI.platform
  const shellThresholdMs = platform === 'win32' ? 700 : 300
  const sep = platform === 'win32' ? '\\' : '/'

  // Helper method
  const waitForGitDiffOpen = async (label: string, timeout = 8000) => {
    return await waitFor(`gitdiff-open:${label}`, () => {
      const api = getGitDiffApi()
      return Boolean(api?.isOpen && api.isOpen())
    }, timeout)
  }

  const waitForGitDiffLoaded = async (label: string, timeout = 12000, minFileCount = 1) => {
    return await waitFor(`gitdiff-loaded:${label}`, () => {
      const api = getGitDiffApi()
      if (!api?.getFileList) return false
      const timing = api.getTiming?.()
      if (!timing || timing.diffLoadedAt === null) return false
      const fileList = api.getFileList()
      if (!Array.isArray(fileList)) return false
      if (fileList.length >= minFileCount) return true
      if (minFileCount === 0) {
        return Boolean(api.getRepoRoot?.())
      }
      return false
    }, timeout)
  }

  const openGitDiff = async (label: string) => {
    window.dispatchEvent(new CustomEvent('git-diff:open', { detail: { terminalId, source: 'debug' } }))
    const opened = await waitForGitDiffOpen(label)
    if (!opened) {
      log('gitdiff-open-failed', { label })
      return false
    }
    return true
  }

  const closeGitDiff = async (label: string) => {
    window.dispatchEvent(new CustomEvent('git-diff:close', { detail: { terminalId } }))
    await sleep(500)
    log('gitdiff-closed', { label })
  }

  /** Execute the command in the terminal and wait */
  const termExec = async (cmd: string, label: string, waitMs = 800) => {
    await window.electronAPI.terminal.write(terminalId, cmd + '\r')
    await sleep(waitMs)
    log(`exec:${label}`, { cmd })
  }

  /** Switch the terminal directory and wait for watcher to sense */
  const cdTo = async (dir: string, label: string) => {
    const shellKind = await resolveTerminalShellKind(terminalId)
    const cdCmd = buildChangeDirectoryCommand(platform, dir, shellKind).trimEnd()
    await termExec(cdCmd, `cd:${label}`)
    await window.electronAPI.git.notifyTerminalActivity(terminalId)
    await sleep(600)
  }

  // List of marked paths used for finishing phase cleanup
  const createdMarkerPaths: string[] = []

  // ==========================================
  // SD-01: Root directory benchmark test - record the file list in the root directory as a comparison
  // ==========================================
  let baselineFileCount = 0
  if (!cancelled()) {
    log('SD-01:start')
    await cdTo(rootPath, 'root')

    const opened = await openGitDiff('SD-01-root')
    if (opened) {
      const loaded = await waitForGitDiffLoaded('SD-01-root', 12000, 0)
      const api = getGitDiffApi()
      baselineFileCount = api?.getFileList()?.length ?? 0
      const repoRoot = api?.getRepoRoot?.() ?? null
      const timing = api?.getTiming?.() ?? null

      _assert('SD-01-root-loads', loaded, {
        fileCount: baselineFileCount,
        repoRoot,
        openToShellMs: timing?.openToShellMs ?? null,
        openToDiffLoadedMs: timing?.openToDiffLoadedMs ?? null
      })
      log('SD-01:baseline', {
        fileCount: baselineFileCount,
        repoRoot,
        openToShellMs: timing?.openToShellMs ?? null,
        openToDiffLoadedMs: timing?.openToDiffLoadedMs ?? null
      })
      await closeGitDiff('SD-01')
    } else {
      _assert('SD-01-root-loads', false, { reason: 'open failed' })
    }
    await sleep(300)
  }

  // ==========================================
  // SD-02: Enter the subdirectory → Create a new file → Open Git Diff → Verify that the file appears
  // ==========================================
  if (!cancelled()) {
    log('SD-02:start')
    const subDir = `${rootPath}${sep}src`
    await cdTo(subDir, 'subdir-src')

    // Create a test file in a subdirectory to generate git changes
    const markerRelPath = `src/${TEST_MARKER_FILE}`
    const markerAbsPath = `${rootPath}${sep}src${sep}${TEST_MARKER_FILE}`
    createdMarkerPaths.push(markerAbsPath)

    if (platform === 'win32') {
      await termExec(`echo autotest-marker > "${TEST_MARKER_FILE}"`, 'create-marker-win')
    } else {
      await termExec(`echo "autotest-marker-$(date +%s)" > "${TEST_MARKER_FILE}"`, 'create-marker')
    }
    let markerCreated = false
    const markerWaitStartedAt = performance.now()
    while (!markerCreated && performance.now() - markerWaitStartedAt < 5000) {
      const result = await window.electronAPI.project.readFile(rootPath, markerRelPath)
      markerCreated = result.success && Boolean(result.content?.includes('autotest-marker'))
      if (!markerCreated) {
        await sleep(120)
      }
    }
    _assert('SD-02-marker-created-before-diff', markerCreated, {
      markerRelPath
    })
    if (!markerCreated || cancelled()) return results
    // Wait extra for git watcher to detect file changes
    await window.electronAPI.git.notifyTerminalActivity(terminalId)
    await sleep(800)

    const startMs = performance.now()
    const opened = await openGitDiff('SD-02-subdir')
    if (opened) {
      const loaded = await waitForGitDiffLoaded('SD-02-subdir')
      const loadMs = Math.round(performance.now() - startMs)
      const api = getGitDiffApi()
      const fileList = api?.getFileList() ?? []
      const fileCount = fileList.length
      const repoRoot = api?.getRepoRoot?.() ?? null
      const cwdProp = api?.getCwd?.() ?? null
      const timing = api?.getTiming?.() ?? null

      // Core assertion 1: The subdirectory can be loaded normally
      _assert('SD-02-subdir-loads', loaded, {
        fileCount,
        loadMs,
        repoRoot,
        cwdProp,
        openToDiffLoadedMs: timing?.openToDiffLoadedMs ?? null,
        openToCwdReadyMs: timing?.openToCwdReadyMs ?? null
      })
      _assert('SD-02-shell-visible-fast', (timing?.openToShellMs ?? Number.MAX_SAFE_INTEGER) < shellThresholdMs, {
        openToShellMs: timing?.openToShellMs ?? null,
        thresholdMs: shellThresholdMs
      })

      // Core Assertion 2: repoRoot resolves to the warehouse root directory, not a subdirectory
      if (repoRoot && cwdProp) {
        const repoRootNorm = repoRoot.replace(/[\\/]+$/, '')
        const subdirNorm = subDir.replace(/[\\/]+$/, '')
        const repoRootUsesForwardSlash = !repoRootNorm.includes('\\')
        const cwdUsesForwardSlash = !cwdProp.includes('\\')
        _assert('SD-02-resolved-to-repo-root', repoRootNorm !== subdirNorm && repoRootUsesForwardSlash && cwdUsesForwardSlash, {
          repoRoot: repoRootNorm,
          subDir: subdirNorm,
          repoRootUsesForwardSlash,
          cwdUsesForwardSlash
        })
      } else {
        _assert('SD-02-resolved-to-repo-root', false, { reason: 'repoRoot or cwdProp is null', repoRoot, cwdProp })
      }

      // Core Assertion 3: Files created in subdirectories appear in the diff file list
      const markerFound = fileList.some(f =>
        f.filename === markerRelPath ||
        f.filename === TEST_MARKER_FILE ||
        f.filename.endsWith(TEST_MARKER_FILE)
      )
      _assert('SD-02-marker-file-visible', markerFound, {
        markerRelPath,
        filesInList: fileList.map(f => f.filename).slice(0, 20),
        totalFiles: fileCount
      })

      log('SD-02:result', { fileCount, loadMs, markerFound, repoRoot })
      await closeGitDiff('SD-02')
    } else {
      _assert('SD-02-subdir-loads', false, { reason: 'open failed' })
      _assert('SD-02-resolved-to-repo-root', false, { reason: 'open failed' })
      _assert('SD-02-marker-file-visible', false, { reason: 'open failed' })
    }
    await sleep(300)
  }

  // ==========================================
  // SD-03: Still in subdirectory → Close and reopen → Verify cache hit (fast loading)
  // ==========================================
  if (!cancelled()) {
    log('SD-03:start')
    const startMs = performance.now()
    const opened = await openGitDiff('SD-03-cache')
    if (opened) {
      const loaded = await waitForGitDiffLoaded('SD-03-cache', 4000)
      const loadMs = Math.round(performance.now() - startMs)
      const api = getGitDiffApi()
      const fileCount = api?.getFileList()?.length ?? 0
      const timing = api?.getTiming?.() ?? null

      _assert('SD-03-cache-hit-fast', loaded && loadMs < 3000, {
        loaded,
        fileCount,
        loadMs,
        openToDiffLoadedMs: timing?.openToDiffLoadedMs ?? null
      })

      log('SD-03:result', { fileCount, loadMs })
      await closeGitDiff('SD-03')
    } else {
      _assert('SD-03-cache-hit-fast', false, { reason: 'open failed' })
    }
    await sleep(300)
  }

  // ==========================================
  // SD-04: Deep subdirectory electron/main → Open Git Diff → Verify repoRoot is correct
  // ==========================================
  if (!cancelled()) {
    log('SD-04:start')
    const deepDir = `${rootPath}${sep}electron${sep}main`
    await cdTo(deepDir, 'deep-subdir')

    const startMs = performance.now()
    const opened = await openGitDiff('SD-04-deep')
    if (opened) {
      const loaded = await waitForGitDiffLoaded('SD-04-deep')
      const loadMs = Math.round(performance.now() - startMs)
      const api = getGitDiffApi()
      const fileCount = api?.getFileList()?.length ?? 0
      const repoRoot = api?.getRepoRoot?.() ?? null
      const timing = api?.getTiming?.() ?? null

      _assert('SD-04-deep-subdir-loads', loaded, {
        fileCount,
        loadMs,
        repoRoot,
        openToDiffLoadedMs: timing?.openToDiffLoadedMs ?? null
      })

      // Verify that repoRoot equals the project root directory
      if (repoRoot) {
        const repoRootNorm = repoRoot.replace(/[\\/]+$/, '')
        const rootNorm = rootPath.replace(/[\\/]+$/, '')
        const repoRootUsesForwardSlash = !repoRootNorm.includes('\\')
        _assert('SD-04-deep-repo-root-matches', repoRootNorm === rootNorm && repoRootUsesForwardSlash, {
          repoRoot: repoRootNorm,
          expected: rootNorm,
          repoRootUsesForwardSlash
        })
      } else {
        _assert('SD-04-deep-repo-root-matches', false, { reason: 'repoRoot is null' })
      }

      // Verification: Markup files previously created in src/ are also visible in deep subdirectories
      const fileList = api?.getFileList() ?? []
      const markerStillVisible = fileList.some(f => f.filename.endsWith(TEST_MARKER_FILE))
      _assert('SD-04-marker-visible-from-deep', markerStillVisible, {
        totalFiles: fileCount
      })

      log('SD-04:result', { fileCount, loadMs, repoRoot, markerStillVisible })
      await closeGitDiff('SD-04')
    } else {
      _assert('SD-04-deep-subdir-loads', false, { reason: 'open failed' })
      _assert('SD-04-deep-repo-root-matches', false, { reason: 'open failed' })
      _assert('SD-04-marker-visible-from-deep', false, { reason: 'open failed' })
    }
    await sleep(300)
  }

  // ==========================================
  // SD-05: Quickly switch on and off 5 times in the subdirectory (stability + no rotation)
  // ==========================================
  if (!cancelled()) {
    log('SD-05:start')
    const subDir = `${rootPath}${sep}src`
    await cdTo(subDir, 'rapid-toggle-subdir')

    let allOk = true
    for (let i = 0; i < 5; i++) {
      if (cancelled()) break
      window.dispatchEvent(new CustomEvent('git-diff:open', { detail: { terminalId, source: 'debug' } }))
      const opened = await waitFor(`sd05-open-${i}`, () => {
        const api = getGitDiffApi()
        return Boolean(api?.isOpen())
      }, 6000)
      if (!opened) { allOk = false; break }
      // Wait for loading to complete (can't keep spinning)
      const loaded = await waitFor(`sd05-loaded-${i}`, () => {
        const api = getGitDiffApi()
        return Boolean(api?.getFileList && api.getFileList().length > 0)
      }, 8000)
      if (!loaded) { allOk = false; break }
      await sleep(200)
      window.dispatchEvent(new CustomEvent('git-diff:close', { detail: { terminalId } }))
      await waitFor(`sd05-close-${i}`, () => {
        const api = getGitDiffApi()
        return !api || !api.isOpen()
      }, 4000)
      await sleep(200)
    }
    _assert('SD-05-rapid-toggle-subdir', allOk, { iterations: 5, allOk })
    await sleep(300)
  }

  // ==========================================
  // Closing: delete the test mark file → return to the root directory
  // ==========================================
  if (!cancelled()) {
    await cdTo(rootPath, 'cleanup-root')
    for (const markerPath of createdMarkerPaths) {
      try {
        if (platform === 'win32') {
          await termExec(`del /q "${markerPath}"`, 'cleanup-marker-win', 500)
        } else {
          await termExec(`rm -f "${markerPath}"`, 'cleanup-marker', 500)
        }
      } catch {
        log('cleanup-marker-error', { markerPath })
      }
    }
    await sleep(300)
  }

  log('git-diff-subdir:done', {
    total: results.length,
    passed: results.filter(r => r.ok).length,
    failed: results.filter(r => !r.ok).length
  })

  return results
}
